/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-09-16 08:12:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.Random;
import java.sql.SQLIntegrityConstraintViolationException;

public final class AddProject_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Random");
    _jspx_imports_classes.add("java.sql.SQLIntegrityConstraintViolationException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Project</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, true);
      out.write("\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function FieldCheck(F, T) {\r\n");
      out.write("		var val = F.value;\r\n");
      out.write("		if (val == \"\") {\r\n");
      out.write("			alert(T + \"is mandatory\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function validate() {\r\n");
      out.write("		if (FieldCheck(proj.pname, 'ProjectName') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (FieldCheck(proj.description, 'Description') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (FieldCheck(proj.sdate, 'date') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (proj.duration.value < 0){\r\n");
      out.write("			alert(\"Duration Cannot be negative\");\r\n");
      out.write("			return false;\r\n");
      out.write("			}\r\n");
      out.write("		if (FieldCheck(proj.duration, 'Duration') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		\r\n");
      out.write("		if (FieldCheck(proj.cname, 'Name') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (FieldCheck(proj.caddress, 'Address') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (FieldCheck(proj.phone, 'Phone') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (FieldCheck(proj.mailid, 'Mailid') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (proj.phoneno.length < 10){\r\n");
      out.write("			alert(\"Invalid Number\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"dateget.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"SC\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<form name=\"proj\" action=\"./AddProj\">\r\n");
      out.write("	<center>\r\n");
      out.write("		<h3>Add Project</h3>\r\n");
      out.write("	</center>\r\n");
      out.write("	<br>\r\n");
      out.write("	<br>\r\n");
      out.write("	<center>\r\n");
      out.write("		<table>\r\n");
      out.write("	\r\n");
      out.write("			<tr>\r\n");
      out.write("			\r\n");
      out.write("				<td>&nbsp;Project Name :</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"pname\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Project Description:</td>\r\n");
      out.write("				<td><textarea name=\"description\" cols=\"20\" rows=\"3\"\r\n");
      out.write("						name=\"description\"></textarea></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Date</td>\r\n");
      out.write("				<td><input type=\"date\" name=\"sdate\" value=\"\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Duration:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"duration\" value=\"\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Client Name:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"cname\" value=\"\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Client Address</td>\r\n");
      out.write("				<td><textarea name=\"caddress\" name=\"caddress\" cols=\"20\"\r\n");
      out.write("						rows=\"3\"></textarea></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Phone No:</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"phoneno\" value=\"\"  pattern=\"98[0-9]{8}\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;EmailId:</td>\r\n");
      out.write("				<td><input type=\"email\" name=\"mailid\" value=\"\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>&nbsp;Department Name:</td>\r\n");
      out.write("				<td><select name=\"deptname\">\r\n");
      out.write("						");

						Connection con;
						PreparedStatement pstmt, pstmt1;
						ResultSet rs = null, rs1 = null;
						try {
							Class.forName("com.mysql.cj.jdbc.Driver");
							con = DriverManager.getConnection("jdbc:mysql://localhost:3306/bts", "root", "");
							pstmt = con.prepareStatement("select * from department_details");

							rs = pstmt.executeQuery();
							while (rs.next()) {
							
      out.write("\r\n");
      out.write("							<option>");
      out.print(rs.getString("dept_name"));
      out.write("</option>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("							\r\n");
      out.write("							</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("							<td>Project Lead:</td>\r\n");
      out.write("							<td><select name=\"plead\">\r\n");
      out.write("							");

							pstmt=con.prepareStatement("select * from employee_details");
					    	rs=pstmt.executeQuery();
					    	while(rs.next())
					    	{
							
      out.write("\r\n");
      out.write("							<option>");
      out.print(rs.getString("loginid") );
      out.write("</option>\r\n");
      out.write("							");

					    	}
							
      out.write("\r\n");
      out.write("							</select>\r\n");
      out.write("							</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("						");

						} catch (Exception e) {
						e.printStackTrace();

						}
						
      out.write("\r\n");
      out.write("		</table><br>\r\n");
      out.write("		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("	\r\n");
      out.write("		<button type=\"submit\" name=\"submit\" onclick=\"return validate()\" >Submit</button>\r\n");
      out.write("		\r\n");
      out.write("	</center>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
