/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-09-19 02:18:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class EditProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Edit Profile</title>\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"testerstyle.css\" type=\"text/css\">\r\n");

if(request.getParameter("cat")!=null){
	if(request.getParameter("cat").equals("Tester")){
		
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./TesterHeader.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}
	
	if(request.getParameter("cat").equals("Developer")){

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./DeveloperHeader.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}
	if(request.getParameter("cat").equals("HrManager")){

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./ManagerHeader.jsp", out, false);
      out.write('\r');
      out.write('\n');

	}
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function ChkMandatoryField(F, T) {\r\n");
      out.write("		var val = F.value;\r\n");
      out.write("		if (val == \"\") {\r\n");
      out.write("			alert(T + \" is mandatory\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function validate() {\r\n");
      out.write("		if (ChkMandatoryField(editform.userid, 'UserId') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.fname, 'FirstName') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		\r\n");
      out.write("		if (ChkMandatoryField(editform.lname, 'LastName') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (editform.gender.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select Gender !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if (ChkMandatoryField(editform.qualification, 'Qualification') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.address, 'Address') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.phoneno, 'PhoneNo') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.mobileno, 'MobileNo') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.emailid, 'EmailID') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.doj, 'Date Of Joining') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		if (editform.role.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select Designation !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (editform.maritalstatus.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select MaritalStatus !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (editform.HintQuestion.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select HintQuestion !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (ChkMandatoryField(editform.hintanswer, 'HintAnswer') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"dateget.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"White\">\r\n");
      out.write("	<form action=\"UpdateProfile?cat=");
      out.print( request.getParameter("cat") );
      out.write("\"\r\n");
      out.write("		method=\"post\">\r\n");
      out.write("		<h3 align=\"center\">\r\n");
      out.write("			<font color=\"red\"> ");
if(request.getParameter("msg")!=null)
{ 
      out.write(' ');
      out.print(request.getParameter("msg"));
      out.write(' ');
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</font>\r\n");
      out.write("		</h3>\r\n");
      out.write("		<center>\r\n");
      out.write("			<h2>\r\n");
      out.write("			Edit Profile\r\n");
      out.write("			</h2>\r\n");
      out.write("		</center>\r\n");
      out.write("		<center>\r\n");
      out.write("			<table>\r\n");
      out.write("				");

		ServletContext sc=getServletContext();
		String driver=sc.getInitParameter("drivername");
		String url=sc.getInitParameter("url");
		String uname=sc.getInitParameter("username");
		String pwd=sc.getInitParameter("password");
		try{
			Class.forName(driver);
			Connection  con=DriverManager.getConnection(url,uname,pwd);
			ResultSet rs;
			HttpSession hs=request.getSession();
			String userid=(String)hs.getAttribute("userid");
			PreparedStatement pstmt=con.prepareStatement("select * from employee_details where loginid=?");
			pstmt.setString(1,userid);
			rs=pstmt.executeQuery();
			
		while(rs.next()){
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>UserId: </td>\r\n");
      out.write("		<td><input type=\"text\" name=\"userid\" value=\"");
      out.print( rs.getString("loginid"));
      out.write("\" readonly></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Fname: </td>\r\n");
      out.write("		<td><input type=\"text\" name=\"fname\" value=\"");
      out.print(rs.getString("fname"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Lname: </td>\r\n");
      out.write("		<td><input type=\"text\" name=\"lname\" value=\"");
      out.print(rs.getString("lname"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Gender: </td>\r\n");
      out.write("		<td><select name=\"gender\">\r\n");
      out.write("		<option>");
      out.print(rs.getString("gender"));
      out.write("</option>\r\n");
      out.write("		<option value=\"select\">---Select---</option>\r\n");
      out.write("		<option value=\"male\">Male</option>\r\n");
      out.write("		<option value=\"female\">Female</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Qualification:</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"qualification\" value=\"");
      out.print(rs.getString("qualification"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Address:</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"address\" value=\"");
      out.print(rs.getString("address"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Phone No:</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"phoneno\" value=\"");
      out.print(rs.getString("phoneno"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Mobile No:</td>\r\n");
      out.write("		<td><input type=\"text\" name=\"mobileno\" value=\"");
      out.print(rs.getString("mobileno"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Email ID:</td>\r\n");
      out.write("		<td><input type=\"email\" name=\"mailid\" value=\"");
      out.print(rs.getString("emailid"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>DOJ:</td>\r\n");
      out.write("		<td><input type=\"date\" name=\"doj\" value=\"");
      out.print(rs.getString("doj"));
      out.write("\" readonly>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Designation:</td>\r\n");
      out.write("		<td>\r\n");
      out.write("		<select name=\"role\">\r\n");
      out.write("			<option>");
      out.print(rs.getString("role"));
      out.write("</option>\r\n");
      out.write("			<option value=\"select\">----select----</option>\r\n");
      out.write("			<option>Tester</option>\r\n");
      out.write("			<option>Manager</option>\r\n");
      out.write("			<option>Developer</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td>Marital Status:</td>\r\n");
      out.write("		<td>\r\n");
      out.write("		<select name=\"maritalstatus\">\r\n");
      out.write("			<option>");
      out.print(rs.getString("maritalstatus") );
      out.write("</option>\r\n");
      out.write("			<option value=\"select\">----select----</option>\r\n");
      out.write("			<option>Married</option>\r\n");
      out.write("			<option>Unmarried</option>\r\n");
      out.write("		</select>\r\n");
      out.write("		</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("		<td><div>Hint Question:</div></td>\r\n");
      out.write("		<td><div align=\"left\">\r\n");
      out.write("             <select name=\"HintQuestion\" class=\"borderBlue\">\r\n");
      out.write("		       <OPTION value=\"select\">[Select One]\r\n");
      out.write("               <OPTION value=\"What is the name of your first school?\">What is the name of your first school?\r\n");
      out.write("               <OPTION value=\"What is your favourite pass-time?\">What is your favourite pass-time?\r\n");
      out.write("               <OPTION value=\"What is your mother maiden name?\">What is your mother's maiden name?\r\n");
      out.write("               <OPTION value=\"What is your favourite food?\">What is your favourite food?\r\n");
      out.write("             </select>\r\n");
      out.write("           </div>\r\n");
      out.write("           </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         \r\n");
      out.write("         <tr>\r\n");
      out.write("			<td>HintAnswer:</td>\r\n");
      out.write("			<td><input type=\"text\" name=\"hintanswer\" value=\"");
      out.print(rs.getString("hintanswer"));
      out.write("\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		");

		}
		}catch(Exception e){
			e.printStackTrace();
		}
		
      out.write("\r\n");
      out.write("		<tr>\r\n");
      out.write("		\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("			<tr>\r\n");
      out.write("			<td colspan=\"2\" align=\"center\"><input type=\"submit\" id=\"btn\" name=\"sub\" value=\"Edit\" onclick=\"return validate()\">\r\n");
      out.write("			<input type=\"Reset\" id=\"btn2\" name=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</center>\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
