/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-09-16 08:14:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Header</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\">\r\n");
      out.write(" <style>ul#nav, ul#nav ul\r\n");
      out.write("	{\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul#nav  li {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav li ul {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin-left: -999em; /* hide menu from view */\r\n");
      out.write("	top: 20;\r\n");
      out.write("	left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Styles for Menu Items */\r\n");
      out.write("ul#nav  li a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: \"black\";\r\n");
      out.write("	padding: 2px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	min-height: 0;\r\n");
      out.write("}\r\n");
      out.write("/* commented backslash mac hiding hack \\*/\r\n");
      out.write("* html ul#nav  li a {\r\n");
      out.write("	height: 1%;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("/* end hack */\r\n");
      out.write("\r\n");
      out.write("/* this sets all hovered lists to black */\r\n");
      out.write("#nav li:hover a, #nav  li.over a, #nav li:hover li a:hover, #nav li.over li a:hover\r\n");
      out.write("	{\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* set dropdown to default */\r\n");
      out.write("#nav li:hover li a, #nav li.over li a {\r\n");
      out.write("	color: black;\r\n");
      out.write("	background-color: silver;\r\n");
      out.write("	*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#nav li ul li a {\r\n");
      out.write("	padding: 2px 2px;\r\n");
      out.write("} /* Sub Menu Styles */\r\n");
      out.write("#nav li:hover ul, #nav li.over ul {\r\n");
      out.write("	margin-left: 0;\r\n");
      out.write("} /* show menu*/\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"white\">\r\n");
      out.write("	<form>\r\n");
      out.write("		<table width=\"100%\" border=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><img src=\"Images/TestTrack_Pro.gif\" height=\"150\"\r\n");
      out.write("					alt=\"Header Image\"></td>\r\n");
      out.write("				<td><font face=\"arial narrow\" size=\"10px\" color=\"#4D2661\"><b>Bug\r\n");
      out.write("							Tracking System</b></font></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				");

				HttpSession hs = request.getSession();
				String uname = (String) hs.getAttribute("userid");
				String role = (String) hs.getAttribute("role");
				
      out.write("\r\n");
      out.write("				<td align=\"right\" valign=\"bottom\" colspan=2><b> ");

 if (("admin").equals(role)) {
 
      out.write("Welcome,&nbsp;&nbsp; Admin");

 } else {
 
      out.write("Welcome,&nbsp;&nbsp;");
      out.print(uname);
      out.write(' ');

 }
 
      out.write("\r\n");
      out.write("</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ");

 if (("admin").equals(role)) {
 
      out.write("<b>[ <a href=\"./AdminHome.jsp\"><font color=\"#FBC61\" size=\"3px\">Home</font></a>] </b>&nbsp;");

 } else if (("Tester").equals(uname)) {
 
      out.write("<b> <a href=\"./TesterHome.jsp?cat=Tester\"><font color=\"#FBC61\" size=\"3px\">Home</font></a>] </b>&nbsp; ");

 } else if (("Developer").equals(uname)) {
 
      out.write("<b> <a href=\"./DeveloperHome.jsp?cat=DEveloper&uname=");
      out.print(uname);
      out.write("\"><font color=\"#FBC61\" size=\"3px\">Home</font></a> ]</b>&nbsp; ");

 } else if (("Manager").equals(uname)) {
 
      out.write("<b> <a href=\"./MangerHome.jsp?cat=HrMangager&uname=");
      out.print(uname);
      out.write("\"><font color=\"#FBC61\" size=\"3px\">Home</font></a>] </b>&nbsp;");

 }
      out.write("\r\n");
      out.write("					 \r\n");

 if (role != "user") {
 
      out.write("<b>[ <a href=\"./Logout.jsp\"><font color=\"#FBC61\" size=\"3px\">Logout</font></a>\r\n");
      out.write("						]\r\n");
      out.write("				</b> ");

 }
 
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<table border=\"0\" align=\"right\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><font size=\"10px\">\r\n");
      out.write("							<ul id=\"nav\">\r\n");
      out.write("								<li><a href=\"#\">Department</a>\r\n");
      out.write("									<ul id=\"nav\">\r\n");
      out.write("										<li><a href=\"./AddDepartment.jsp\">Add&nbsp;Department&nbsp;</a></li>\r\n");
      out.write("										<li><a href=\"./ViewDepartment.jsp\">View&nbsp;Departments</a></li>\r\n");
      out.write("										<li><a href=\"./UpdateDepartment.jsp\">Update&nbsp;Departments</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a href=\"#\">Employee </a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"./ViewEmployee.jsp\">View&nbsp;Employee&nbsp;</a></li>\r\n");
      out.write("										<li><a href=\"./UpdateEmployee.jsp\">Update&nbsp;Employee</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("								<li><a href=\"#\">Project </a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"./AddProject.jsp\">Add Project</a></li>\r\n");
      out.write("										<li><a href=\"./ViewProject.jsp\">View Project</a></li>\r\n");
      out.write("										<li><a href=\"./UpdateProject.jsp\">Update&nbsp;Project</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("\r\n");
      out.write("								<li><a href=\"#\">Permission </a>\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"./EmployeePermission.jsp\">Employee</a></li>\r\n");
      out.write("									</ul></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("					</font></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
