/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-09-16 15:03:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function ChkMandatoryField(F, T) {\r\n");
      out.write("		var val = F.value;\r\n");
      out.write("		if (val == \"\") {\r\n");
      out.write("			alert(T + \" is mandatory\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function validate() {\r\n");
      out.write("		if (ChkMandatoryField(editform.userid, 'UserId') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.fname, 'FirstName') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.lname, 'LastName') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (editform.gender.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select Gender !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (ChkMandatoryField(editform.qualification, 'Qualification') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.address, 'Address') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.mobileno, 'MobileNo') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.emailid, 'EmailID') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		if (ChkMandatoryField(editform.doj, 'Date Of Joining') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("\r\n");
      out.write("		if (editform.designation.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select Designation !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (editform.maritalstatus.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select MaritalStatus !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (editform.HintQuestion.value == \"select\") {\r\n");
      out.write("			window.alert(\"Select HintQuestion !\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (ChkMandatoryField(editform.hintanswer, 'HintAnswer') == false)\r\n");
      out.write("			return false;\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"dateget.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"white\">\r\n");
      out.write("\r\n");
      out.write("	<form action=\"./Reg\" name=\"editform\" onsubmit=\"return validate()\">\r\n");
      out.write("		<table width=\"100%\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><img alt=\"HeaderImage\" src=\"./Images/Header.png\"\r\n");
      out.write("					height=\"120\"></td>\r\n");
      out.write("				<td><font face=\"arial narrow\" size=\"10px\" color=\"#4D2661\"><b>Bug\r\n");
      out.write("							Tracking System</b></font></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"right\" colspan=\"2\"><b>[<a href=\"./Home.jsp\"><font\r\n");
      out.write("							color=\"#FBC61\" size=\"3px\">Home</font></a>]\r\n");
      out.write("				</b></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<center>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td><h4>REGISTRATION FORM</h4></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</center>\r\n");
      out.write("		<center>\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>UserId:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"userid\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Fname:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"fname\" value=\"\" pattern=\"[A-Za-z]{}\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Lname:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"lname\" value=\"\" pattern=\"[A-Za-z]{}\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Gender:</td>\r\n");
      out.write("					<td><select name=\"gender\">\r\n");
      out.write("							<option value=\"select\">-----select----</option>\r\n");
      out.write("							<option>Male</option>\r\n");
      out.write("							<option>Female</option>\r\n");
      out.write("							</select>\r\n");
      out.write("							</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Qualification:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"qualification\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Address:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"address\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>PhoneNo:</td>\r\n");
      out.write("					<td><input type=\"tel\" name=\"phoneno\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>MobileNo:</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"mobileno\" value=\"\" pattern=\"9[7-8]{1}[0-9]{8}\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>EmailID:</td>\r\n");
      out.write("					<td><input type=\"email\" name=\"mailid\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>DOJ</td>\r\n");
      out.write("					<td><input type=\"date\" name=\"doj\" value=\"\"> </td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Designation:</td>\r\n");
      out.write("					<td><select name=\"designation\">\r\n");
      out.write("							<option value=\"select\">-----select----</option>\r\n");
      out.write("							<option>Developer</option>\r\n");
      out.write("							<option>Tester</option>\r\n");
      out.write("							<option>Manager</option>\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>MaritalStatus:</td>\r\n");
      out.write("					<td><select name=\"maritalstatus\">\r\n");
      out.write("							<option value=\"select\">-----select----</option>\r\n");
      out.write("							<option>Married</option>\r\n");
      out.write("							<option>Unmarried</option>\r\n");
      out.write("					</select></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>Password</td>\r\n");
      out.write("					<td><input type=\"password\" name=\"password\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td class=\"text1\">Hint\r\n");
      out.write("							Question</div></td>\r\n");
      out.write("					<td><div align=\"left\">\r\n");
      out.write("							<select name=\"HintQuestion\" class=\"borderBlue\">\r\n");
      out.write("								<OPTION value=\"select\">[Select One]\r\n");
      out.write("								<OPTION value=\"What is the name of your first school?\">What\r\n");
      out.write("									is the name of your first school?\r\n");
      out.write("								<OPTION value=\"What is your favourite pass-time?\">What\r\n");
      out.write("									is your favourite pass-time?\r\n");
      out.write("								<OPTION value=\"What is your mother maiden name?\">What\r\n");
      out.write("									is your mother's maiden name?\r\n");
      out.write("								<OPTION value=\"What is your favourite food?\">What is\r\n");
      out.write("									your favourite food?\r\n");
      out.write("							</select>\r\n");
      out.write("						</div></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>HintAnswer</td>\r\n");
      out.write("					<td><input type=\"text\" name=\"hintanswer\" value=\"\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td><input type=\"submit\" name=\"sub\" value=\"Register\">\r\n");
      out.write("					 <input type=\"Reset\" name=\"reset\" value=\"Reset\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</center>\r\n");
      out.write("	</form>\r\n");
      out.write("	</body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "./Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
