/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-08-11 04:47:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TesterHeader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"menu.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Tester Header</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("sfHover = function() {\r\n");
      out.write("   var sfEls = document.getElementById(\"nav\").getElementsByTagName(\"LI\");\r\n");
      out.write("   for (var i=0; i<sfEls.length; i++) {\r\n");
      out.write("      sfEls[i].onmouseover=function() {\r\n");
      out.write("         this.className+=\" over\";\r\n");
      out.write("      }\r\n");
      out.write("      sfEls[i].onmouseout=function() {\r\n");
      out.write("         this.className=this.className.replace(new RegExp(\" over\\\\b\"), \"\");\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("if (window.attachEvent) window.attachEvent(\"onload\", sfHover);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"SC\">\r\n");
      out.write("	<form>\r\n");
      out.write("		<table width=\"100%\" border=\"0\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td align=\"\"><img alt=\"HeaderImage\" src=\"./Images/Header.png\"\r\n");
      out.write("					height=\"120\"></td>\r\n");
      out.write("				<td align=\"\"><font face=\"arial narrow\" size=\"10px\"\r\n");
      out.write("					color=\"#4D2661\"><b>Bug Tracking System</b></font></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				");

				HttpSession hs = request.getSession();
				String uname = (String) hs.getAttribute("userid");
				String role = (String) hs.getAttribute("role");
				
      out.write("\r\n");
      out.write("				<td align=\"right\" valign=\"bottom\" colspan=\"2\"><b> ");

if (("admin").equals(role)) {

      out.write("Welcome,&nbsp;&nbsp; Admin");

 } else {
 
      out.write("Welcome,&nbsp;&nbsp;");
      out.print(uname);
      out.write(' ');

 }
 
      out.write("\r\n");
      out.write("</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <b>[ ");

if(("admin").equals(role)){
 
      out.write("<a href=\"./AdminHome.jsp\"> ");

 } else if(("Tester").equals(role)){
 
      out.write("<a href=\"./TesterHome.jsp?cat=Tester\"> ");

 } else if(("Developer").equals(role)){
 
      out.write("<a href=\"./DeveloperHome.jsp?cat=Developer\"> ");

 } else if(("HRManager").equals(role)){
 
      out.write("<a href=\"./ManagerHome.jsp?cat=HrManager\"> ");

 }
 
      out.write("<font color=\"#FBC61\">Home</font>\r\n");
      out.write("								</a> ]</b>&nbsp; ");

 if (role != "user") {
 
      out.write("<b>[ <a href=\"./Logout.jsp\"><font color=\"#FBC61\">logout</font></a>]</b> ");

 }
 
      out.write("</td>\r\n");
      out.write("		</table>\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<form>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<table border=\"0\" align=\"right\">\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<ul id=\"nav\">\r\n");
      out.write("	<li><a href=\"#\">Open</a>\r\n");
      out.write("	<ul id=\"nav\">\r\n");
      out.write("	<li><a href=\"./AssignBug.jsp?cat=Tester\">Bug Report</a></li>\r\n");
      out.write("       <li><a href=\"./ViewBugs1.jsp?cat=Tester\">View Bugs</a></li>\r\n");
      out.write("       <li><a href=\"./EditProfile.jsp?cat=Tester\">Edit Profile</a></li> \r\n");
      out.write("       <li><a href=\"./ChangePassword.jsp?cat=Tester\">Change Password</a></li> \r\n");
      out.write("	</ul>\r\n");
      out.write("	</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<br>\r\n");
      out.write("	\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
